# https://docs.travis-ci.com/user/languages/python/
language: python
python:
 - "3.8"

before_install:
    sudo apt-get upgrade && sudo apt-get -y install make

install:
    make install

script:
    make test
